planeDepth : 80             # clipping plane for the subduction zone, sets cmi depth

spatiallyVariable : False   # whether or not smoothing is uniform or spatially variable

smoothing : 
  fault : 4.0e+14
  cmi : 1.0e+16

# specifies dimensions of cmi for corners not connected to fault
cmi :
  minLon : 125
  minLat : 34

# weighting values for the constraint matrices
constraint : 
  faultEdge : 1.0e+4
  cmiEdge : 5.0e+2
  noTopConstraint: False

inputs :
  fault : "./meshes/japan.msh"
  gps : "./data/cumulative_disp.txt"

results :
  saveFigures : True        # true false figures saved to output directory
  saveData: True            # numerical data results saved to output directory
  saveNumpy: True           # saves numpy files for predDisp, estSlip, cmiDisp, and faultDisp

  # specific figures
  afterslip: True           # fault afterslip magnitude
  dipSlip: True             # dip slip component of fault
  slipLocation: True        # location of peak afterslip
  slipDist : True           # slip distribution of both fault and cmi slip
  dispByComponent : True    # displacements separated by source (from cmi, from fault)
  totalDisp : True            # figure with total gps displacement, predicted and observed
  residuals : True           # gps displacement residuals 

  # organizational info
  testName : ""
  outputDir: ""
