planeDepth : 80             # clipping plane for the subduction zone, sets cmi depth

spatiallyVariable : False   # whether or not smoothing is uniform or spatially variable

smoothing : 
  fault : 4.0e+14
  cmi : 1.0e+16

cmi :
  minLon : 125
  minLat : 34

constraint : 
  faultEdge : 1.0e+4
  cmiEdge : 5.0e+2

inputs :
  fault : "japan.msh"
  cmi : "horiz"               # written by meshCmi in prepareMeshes.py
  gps : "cumulative_disp_seafloor.txt"

results :
  saveFigures : True # true false figures saved to current directory
  slipDist : True # slip distribution figure
  dispSep : True  # displacements separated by component (from cmi, from fault)
  allDisp : True # figure with total displacement, predicted and observed
  ratioFig : True # ratio of cmi displacement to total displacement
  residFig : True # displacement residuals figure
  saveData: True # numerical data results
  testName : ""
